### ISSUE TITLE
Something wrong with FLAC

### ISSUE THREAD

**Issue by muezis** [lakiluki1/Deezium#1]
Hey man, are you sure that FLAC playback is working correctly? Because the sound is like 128kbs/sec. Maybe your extension gives the ability to unlock FLAC for choice, but the stream is still at 128kbs/sec?

**Comment by lakiluki1** [comment]
Hey,

Yes, the FLAC playback should be working correctly. You can easily check this by opening up the  network tab in the developer tools of your browser and checking the format or the downloaded size of the transferred media, which should differ quite a bit (for example, a 4MB transfer for 128kb and like 40MB for FLAC).

If you're willing to put in the extra work, you can also record your system's raw audio output, encode it afterwards and use something like Spek for spectrum analysis and comparison. Here's an example of my system's output when streaming 128KB (left) and FLAC (right), from Deezer on Firefox using the extension (both encoded in FLAC afterwards for easier comparison)
https://i.imgur.com/LG9sci7.jpg

This could also be a browser issue, as FLAC support is still kind of limited in quite a lot of browser, and Deezer doesn't officially support FLAC streaming in browser, but rather in their Electron client.

So, what browser (name + version) and OS are you using? Also, please note that the Chrome extension is kind of still unstable and the Firefox one is preferred.

**Comment by muezis** [comment]
Yes, in network tab, this is the same size as flac. 

Perhaps the problem is that in some tracks is fake-flac. I downloaded it using Deezloader and you can see the result on the screenshot. https://imgur.com/a/VTPGxVl This has .flac and size 25.7 MB. But this is certainly not the fault of the extension. It's just Deezer.

So most likely, FLAC playback works really well. I'm using the latest version of Yandex Browser (This is on Chromium), on Windows 10. Your extension works great. Huge respect for your work. I hope they don't break it. And thank you for answering me and helping me figure it out

By the way, despite the fact that it is already version 1.1, Chrome and Yandex have written version 0.5.  https://imgur.com/a/x9vFE6t

**Comment by lakiluki1** [comment]
Great find! Yes, I guess that explains it. In this case, the FLAC seems to be transcoded from a lossy, 128kbps MP3, which is definitely kind of odd (I'm guessing then that the 320kbps MP3 might also be a transcoded 128kbps). However, this still seems to be the exception, rather than the rule. But yeah, that's Deezer's fault of hosting some FLAC files that are obviously transcoded from a lossy source, and it kind of makes me wonder how many more lossy transcoded FLAC files they host, while advertising them as "High Fidelity".

You're very much welcome, and I really appreciate all of the feedback, it's nice to know someone actually uses this :)

And nice catch on the version, that's because it is actually version 0.5 in the Chrome manifest file, while the GitHub release is 1.1. Truth be told, it's probably much closer to 0.5 than it is to a 1.1 release, and I kind of chose the versions at random.
