### ISSUE TITLE
I can't install extrension 

### ISSUE THREAD

**Issue by HRVAT007** [lakiluki1/Deezium#3]
Title, I press the file when it downloads but nothing happens.

**Comment by anlakii** [comment]
Hey,

what browser are you using? If opening the file from the downloads window does nothing, try dragging and dropping the xpi/crx file to your browser's addon settings page, it should prompt you to install it. But then again, that largely depends on the browser used.

**Comment by HRVAT007** [comment]
![image](https://user-images.githubusercontent.com/23155989/80546965-523d7000-89b7-11ea-9113-67d00dffd48f.png) Google Chrome
Instalirat ću Firefox pa ću vidit hoće li radit. Radi na Mozilli.

**Comment by anlakii** [comment]
This is an issue where Google Chrome >75 no longer allows packed extensions to be installed manually (ie. installing them from third party sources, not from the Chrome Web Store).

It seems there's currently no way to fix this, other than loading it as an unpacked extension or just using a different Chromium based browser (for example, Chromium and Brave seem to work just fine), or deploying the extension to the Chrome Web Store, which I don't think is an option, since I doubt something like this would ever get approved.

**Comment by HRVAT007** [comment]
Kao što sam i napiso, na mozilli radi, na Chromu ne radi al dobro svejedno hvala.
